### PR TITLE
Pass image_range to ExperimentListTemplateImporter

### LINKED ISSUE #490: xia2 complains about missing images even if outside of specified range
```
$ cp $(dials.data get -q x4wide)/*.cbf .
$ xia2 image=X4_wide_M1S4_2_0001.cbf:1:29 read_all_image_headers=false
```
Related to (but not entirely solved by) dials/dials#1333 and cctbx/dxtbx#191.

### PR DESCRIPTION
**Pull request by rjgildea**
This means that xia2 doesn't complain about missing images if they lie outside the start:end specified on the command line.
Only affects read_image_headers=False (i.e. loading the dxtbx imageset from a template).

Fixes #490.

See also cctbx/dxtbx#191 and dials/dials#1333.

### CODE REVIEW

**Comment by rjgildea** [comment]
Needs a test adding.

**Comment by rjgildea** [comment]
If start:end is not set for a given template, then the behaviour should be exactly as before this PR. Standalone testing of this area of the code is made tricky by the excessive use of singletons (e.g. CommandLine object) that require jumping through some hoops to reliably test outside of running a full xia2 job (which is expensive).

**Comment by graeme-winter** [comment]
Please could you remerge master into this so we have the resolutionizer fixes? Without this cannot test...

**Comment by graeme-winter** [comment]
<- would like to test e.g. `xia2 image=~/data/foo/bar_0001.cbf.gz:1:2400:800`

**Comment by graeme-winter** [comment]
@rjgildea  👍 

Testing now but 1st glance seems to be all good

**Pull request merged**
