### PR TITLE
xia2.overload for Eiger

### LINKED ISSUE #412: xia2.overload: support Eiger detectors

### PR DESCRIPTION
**Pull request by graeme-winter**
Fixes #412 

 - change to using ExperimentListFactory "properly"
 - use experiment models not image set ones
 - use imageset get raw data for analysis
 - remove assumptions about CBF files

Also seems to still work in parallel 🤷‍♂️

### CODE REVIEW

**Comment by graeme-winter** [comment]
Seems to be enough changes (with the fix from @Anthchirp which I cherry picked in) that screen19 now works for Eiger data

**Comment by graeme-winter** [comment]
@Anthchirp nice change set thanks 🙂

**Comment by Anthchirp** [comment]
cherry-picking in the commit causes merge problem. should have merged in master or rebased on master

**Comment by graeme-winter** [comment]
Yeh, in hindsight I see this, sorry 😕

**Pull request merged**
