### PR TITLE
Factor in batch offsets in imagesets

### LINKED ISSUE #462: Removing one image breaks xia2 pipeline=dials
```
mv th_8_2_0355.cbf.gz th_8_2_0355.fbc.zg
```

then

```
xia2 ~/data/i04_bag_training/
```

giveth

```
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../conda_base/python.app/Contents/MacOS/python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpp1jetefg
Starting directory: /private/tmp/missing
Working directory: /private/tmp/missing
Free space:        58.09 GB
Host: Grey-Area
Contact: xia2.support@gmail.com
XIA2 0.7.8-gb81a98ab
DIALS 3.dev.8-gf39c16d72
CCP4 7.0.076
Command line: xia2 /Users/graeme/data/i04_bag_training/
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(358): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(350): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(350): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/model/scan.h(350): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
Error: can't convert negative value to unsigned int
Please send the contents of xia2.txt, xia2-error.txt and xia2-debug.txt to:
xia2.support@gmail.com
```

### PR DESCRIPTION
**Pull request by graeme-winter**
Factor in batch offsets when getting subsets of imagesets - this fixes the case
of one or so missing images in a sweep, need to verify that the other use
cases are not affected negatively by this change.

Fixes #462

### CODE REVIEW

**Comment by graeme-winter** [comment]
OK, so this means xia2 now works however throws an error at the end:

```
For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           1.17    3.18    1.17
Low resolution limit                           53.92   53.98    1.19
Completeness                                   82.1   100.0     7.1
Multiplicity                                    4.5     5.3     1.0
I/sigma                                        11.4    49.4     0.6
Rmerge(I)                                     0.070   0.031   0.321
Rmerge(I+/-)                                  0.062   0.029   0.000
Rmeas(I)                                      0.078   0.035   0.454
Rmeas(I+/-)                                   0.076   0.035   0.000
Rpim(I)                                       0.034   0.015   0.321
Rpim(I+/-)                                    0.044   0.019   0.000
CC half                                       0.999   0.999   0.821
Wilson B factor                              10.170
Anomalous completeness                         71.2    99.1     0.3
Anomalous multiplicity                          2.5     3.1     1.0
Anomalous correlation                        -0.029   0.031   0.000
Anomalous slope                               0.861
dF/F                                          0.080
dI/s(dI)                                      0.795
Total observations                           317935   25145     309
Total unique                                  70801    4738     299
Assuming spacegroup: P 41 21 2
Unit cell (with estimated std devs):
57.78387(8) 57.78387(8) 149.9941(3)
90.0        90.0         90.0      
mtz_unmerged format:
Scaled reflections (NATIVE): /private/tmp/missing/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
mtz format:
Scaled reflections: /private/tmp/missing/DataFiles/AUTOMATIC_DEFAULT_free.mtz
Error: can't convert negative value to unsigned int
Please send the contents of xia2.txt, xia2-error.txt and xia2-debug.txt to:
xia2.support@gmail.com
```

**Comment by rjgildea** [comment]
It should be relatively easy to add a test for this use case - a standalone test of the `load_imagesets` function with a single missing image should probably do the trick?

**Comment by graeme-winter** [comment]
Turns out a little bit more was needed but this is now working - I think this has the complete change set to keen for a squash merge. I think there is probably scope for more cleanup but that may be out of context for this PR.

**Comment by graeme-winter** [comment]
Additional - running `xia2 image=~/data/ins-300/INS1_1_0001.cbf.gz:201:300` with master and the branch the diffs are null:

```5c5
< CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpzmfupcwh
---
> CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpce__21in
8c8
< Free space:        21.82 GB
---
> Free space:        21.83 GB
11c11
< XIA2 0.7.11-g349e2868-batch-offset-462
---
> XIA2 0.7.24-g98eb2fd2
99c99
< Processing took 00h 01m 55s
---
> Processing took 00h 01m 53s
```

so has not messed up anything with _which_ frames are processed.

**Comment by graeme-winter** [comment]
@rjgildea tests += `test_load_imageset`

**Pull request merged**
