### PR TITLE
Extend xia2.mmcif with unmerged reflection mmCIF data from DIALS

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
For #534

Add the mmCIF block created by `dials.export format=mmcif` to the `xia2.mmcif` file.

TODO: Also add unmerged data to xia2.mmcif for `scaler = ccp4a, 3dii` ?

### CODE REVIEW

**Comment by jbeilstenedmands** [comment]
For adding mmcif data for non-dials pipelines, my thought was to extract as much information as possible from the scaled_unmerged.mtz output files. GEMMI is easily able to do this (https://project-gemmi.github.io/wasm/to_mmcif/), so is it time to revisit https://github.com/dials/dials/issues/1266 ?
We would retain the ability to write more information from DIALS processing direct to mmcif, however the final output mmcif files may look different from dials vs non-dials pipelines.

**Comment by dagewa** [comment]
I'm very much in favour of using Gemmi for all things cif. It is very fast and well documented.

**Comment by jbeilstenedmands** [comment]
Okay, so I think this now works* for all pipelines, subject to some minor polishing, and should correctly handle MAD and multi-sweep datasets.

For pipeline=dials, this just picks up the mmcif from dials.export. For 3dii or dials-aimless, data is picked up from the mtz files and written into sections based on PROJECT_CRYSTAL_WAVE - so each of these sections has the merging stats and the unmerged data, and a PROJECT_CRYSTAL section contains the metadata regarding the physical crystal, scan and wave relationships.

I may look at the way dials.export writes mmcif data to see if I can make this more consistent with the layout here.

*3dii pipeline currently doesn't write the correct scan angle range as this is missing from mtz batch headers.

**Comment by graeme-winter** [comment]
@jbeilstenedmands please can we make the CIF output _optional_? I don't mind the default being that we do output it, but if ${USER} wants to process some data in a hurry and has no interest in mmCIF output it seems wasteful to make such output mandatory

**Comment by dagewa** [comment]
Note I recommend `bz2` compression for these output files to avoid wasting bytes. Also note that mmCIF output is still rather slow (see https://github.com/dials/dials/issues/1485 for some tests).

**Comment by jbeilstenedmands** [comment]
An update; this is now in better shape, with a consistently formatted mmcif output across the pipelines.

The output contains a data_xia2 block which contains software information and citations and some overall information like two theta refined cell, symmetry and wavelength information. Then there is a data block for each 'WAVE' i.e. data_AUTOMATIC_DEFAULT_NATIVE or data_AUTOMATIC_DEFAULT_WAVE1, data_AUTOMATIC_DEFAULT_WAVE2 etc. Each of these has cell and scan information as well as the merging statistics and unmerged data for that wavelength.

This PR also does some tidying up whilst there, notably removing unused citations. I have also made a versions custom dictionary, to determine program versions only when requested. I don't expect people to look over all this code, but would be useful to know that people are happy with the output mmcif file.

**Comment by jbeilstenedmands** [comment]
Think has a few more changes on the way, which will be done by the end of today/this weekend ready for dials 3.3

**Pull request merged**
