### PR TITLE
Only exclude outliers if resolution limit set

### LINKED ISSUE #388: Excessive outlier rejection in pipeline=3dii
The following xia2 command ended up running almost 200 (!) cycles of outlier rejection/scaling with XSCALE, which seems a little excessive:
```
$ xia2 pipeline=3dii image=/dls/i23/data/2019/nr23571-22/gw/thaumatin/20191127/th_1_11keV/thaumatin_1_00001.cbf
$ grep "Excluding outlier reflections" xia2.txt | wc -l
193
$ ls DEFAULT/scale/*_XSCALE.INP | wc -l
195
```

### PR DESCRIPTION
**Pull request by rjgildea**
Otherwise we end up trying to exclude wilson outliers using
reflections that are beyond the diffraction limit, which can lead
to 100s of cycles of outlier rejection.

Fixes #388

### CODE REVIEW

**Comment by rjgildea** [comment]
Example data set:

With latest dials release:
```
module load dials
xia2 image=/dls/i04-1/data/2020/lb18145-156/Mpro/Mpro-x2092/Mpro-x2092_1_0001.cbf:1:400 min_images=3 pipeline=3dii read_all_image_headers=False trust_beam_centre=True hdf5_plugin=durin-plugin.so atom=S project=AUTOMATIC crystal=DEFAULT resolution.cc_half_significance_level=0.1
```
130 cycles of outlier rejection, with xia2 taking a total of 41m 10s:
```
$ grep "Excluding outlier reflections" xia2.txt | wc -l
130
$ grep "Processing took" xia2.txt 
Processing took 00h 41m 10s
```

Using the changes in this PR, now only 14 cycles of outlier rejection:
```
$ grep "Excluding outlier reflections" xia2.txt | wc -l
14
```

**Comment by graeme-winter** [comment]
testing now

**Comment by graeme-winter** [comment]
Well, that was much quicker

Does make a difference to the answers:

```
For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           1.66    4.51    1.66
Low resolution limit                           52.61   52.64    1.69
Completeness                                   98.4    99.2    96.1
Multiplicity                                    3.8     3.9     3.5
I/sigma                                         3.6    13.8     0.2
Rmerge(I)                                     0.191   0.042   3.927
Rmerge(I+/-)                                  0.166   0.036   3.558
Rmeas(I)                                      0.222   0.048   4.640
Rmeas(I+/-)                                   0.223   0.049   4.804
Rpim(I)                                       0.112   0.024   2.433
Rpim(I+/-)                                    0.148   0.033   3.207
CC half                                       0.996   0.999   0.091
Wilson B factor                              16.320
Anomalous completeness                         94.6    98.3    87.9
Anomalous multiplicity                          2.0     2.1     1.8
Anomalous correlation                        -0.006  -0.064  -0.008
Anomalous slope                               1.017
dF/F                                          0.139
dI/s(dI)                                      0.792
Total observations                           222522   11905    9901
Total unique                                  58894    3085    2863
```

with the branch vs. 

```
High resolution limit                           1.66    4.51    1.66
Low resolution limit                           52.61   52.64    1.69
Completeness                                   99.7    99.7    99.7
Multiplicity                                    3.8     3.9     3.4
I/sigma                                         3.8    13.9     0.3
Rmerge(I)                                     0.180   0.040   2.759
Rmerge(I+/-)                                  0.157   0.035   2.574
Rmeas(I)                                      0.209   0.047   3.263
Rmeas(I+/-)                                   0.211   0.047   3.477
Rpim(I)                                       0.106   0.024   1.715
Rpim(I+/-)                                    0.140   0.032   2.321
CC half                                       0.997   0.999   0.281
Wilson B factor                              15.680
Anomalous completeness                         95.8    98.9    91.1
Anomalous multiplicity                          2.0     2.1     1.8
Anomalous correlation                        -0.013   0.009  -0.030
Anomalous slope                               1.016
dF/F                                          0.134
dI/s(dI)                                      0.790
Total observations                           225088   11970   10231
Total unique                                  59662    3101    2970

```

with master

**Comment by graeme-winter** [comment]
Please could you add a news fragment 😉

**Comment by graeme-winter** [comment]
Further inspection - it looks like _not_ doing any outlier rejection at all gives better results - 

cc_one_half

I suspect if we don't set the outlier list XDS removes them by itself now (which could be new behaviour) whereas if we use the `REMOVE.HKL` feature it does not do this. May be we just want to change the default value for the `keep_outlier` option?

**Comment by graeme-winter** [comment]
That looks like a hard nope - 

```
Grey-Area scale :) $ grep ' 1    10    -5' NATIVE.HKL 
     1    10    -5  1.245E+06  5.342E+04  1427.5  1431.8   348.8  -63.45 1
```

is one example from the alien table - 

```
    1   10   -5    5.10   10.47  0.1253E+07  0.2748E+05 "alien"
```

With the outlier mode in the PR we are eliminating this one - 

```
Grey-Area scale :( $ grep '^1 10 -5 ' REMOVE.HKL 
1 10 -5 10.810000
Grey-Area scale :) $ grep ' 1    10    -5' NATIVE.HKL 
Grey-Area scale :( $ 
```

<oh> that is weird

In `master` with the default mode we have:

```
Grey-Area scale :) $ grep '^1 10 -5 ' REMOVE.HKL 
1 10 -5 10.810000
```

and 

```
Grey-Area scale :) $ grep ' 1    10    -5' NATIVE.HKL 
     1    10    -5  1.242E+06  5.320E+04  1427.5  1431.8   348.8  -63.45 1
```

it is included in the output - aha - 

```
Grey-Area scale :) $ wc -l REMOVE.HKL 
   34930 REMOVE.HKL
```

From XDS_DOC - 

"XSCALE checks for the presence of a file named REMOVE.HKL in the current directory. A file of this name can be provided by the user to specify the indices of reflections that should be excluded from the scaled output file. Each record of REMOVE.HKL consists of the reflection indices h, k, l and possibly other information that will be ignored. Up to 10000 reflections can be specified."

=> we are wasting our time here big time 🤦‍♂️ because we are spending ages generating outlier tables we are not using - which probably explains why the results from ignoring and keeping outliers are about the same, whereas excluding outliers after deciding resolution limits makes a difference as the first 1,000 outliers are probably in the high resolution region which will be excluded anyways.

Let's not merge this PR...

**Comment by graeme-winter** [comment]
Alternative: merge this then we change the default switch value to keep the outliers in, and if we are throwing them out use the code in here. That way at least we know it _is_ throwing away reflections which could otherwise be kept.

**Pull request merged**
