### PR TITLE
Fix Windows tests

### PR DESCRIPTION
**Pull request by dagewa**
WIP branch to resolve issues with tests on Windows. First commit ensures that `".bat"` is added to the dispatcher names when called with `subprocess.run` with `shell=False`.

### CODE REVIEW

**Comment by dagewa** [comment]
@namannimmo10, James told me this might be of interest to you

**Comment by namannimmo10** [comment]
Nice, thank you much!

**Comment by dagewa** [comment]
Here is a report detailing 24 tests that still fail for me locally (from a run of `pytest -n auto --regression --html=xia2-report.html --self-contained-html`): [xia2-report.zip](https://github.com/xia2/xia2/files/14240154/xia2-report.zip). These are more difficult to debug as many of them occur within subprocess calls to xia2 scripts.

There is another class of `UnicodeDecodeError` though that might be easier to look at.

**Comment by dagewa** [comment]
Many remaining errors look like a byte string that starts `--- Logging error ---` being written to stderr, like the below. However, running the `xia2.ssx` command directly in the shell completes correctly. So this may be something weird related to running it as a subprocess, within a pytest session

```
Error	tests/regression/test_ssx.py::test_slice_cbfs::setup	00:01:25	
[gw5] win32 -- Python 3.10.13 C:\Users\fcx32934\sw\cctbx\conda_base\python.exe

dials_data = <DataFetcher: c:\Users\fcx32934\sw\cctbx\build\dials_data>
tmp_path = WindowsPath('C:/Users/fcx32934/AppData/Local/Temp/pytest-of-fcx32934/pytest-125/popen-gw5/test_slice_cbfs0')

    @pytest.fixture
    def refined_expt(dials_data, tmp_path):
        ssx = dials_data("cunir_serial", pathlib=True)
    
        cmd = "xia2.ssx"
        if os.name == "nt":
            cmd += ".bat"
        args = [
            cmd,
            "steps=None",
            "unit_cell=96.4,96.4,96.4,90,90,90",
            "space_group=P213",
        ]
        args.append("image=" + os.fspath(ssx / "merlin0047_1700*.cbf"))
    
        result = subprocess.run(args, cwd=tmp_path, capture_output=True)
>       assert not result.returncode and not result.stderr
E       assert (not 0 and not b'--- Logging error ---\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\fcx32934\\sw\\cctbx\\conda_base\\l...0   96.70  90.00  90.00  90.00\\n                     0.09    0.09    0.09   0.00   0.00   0.00\'\r\nArguments: ()\r\n')
E        +  where 0 = CompletedProcess(args=['xia2.ssx.bat', 'steps=None', 'unit_cell=96.4,96.4,96.4,90,90,90', 'space_group=P213', 'image=c...   96.70  90.00  90.00  90.00\\n                     0.09    0.09    0.09   0.00   0.00   0.00\'\r\nArguments: ()\r\n').returncode
E        +  and   b'--- Logging error ---\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\fcx32934\\sw\\cctbx\\conda_base\\l...0   96.70  90.00  90.00  90.00\\n                     0.09    0.09    0.09   0.00   0.00   0.00\'\r\nArguments: ()\r\n' = CompletedProcess(args=['xia2.ssx.bat', 'steps=None', 'unit_cell=96.4,96.4,96.4,90,90,90', 'space_group=P213', 'image=c...   96.70  90.00  90.00  90.00\\n                     0.09    0.09    0.09   0.00   0.00   0.00\'\r\nArguments: ()\r\n').stderr

tests\regression\test_ssx.py:199: AssertionError
```

**Comment by dagewa** [comment]
Hi @jbeilstenedmands, Charles mentioned various test failures on Windows for the CCP4 9.0 build, and I remembered this PR. This doesn't solve all test issues, but does get us closer, so perhaps it is worth merging?

**Comment by dagewa** [comment]
Bump?

**Review by jbeilstenedmands — APPROVED** [review]

**Pull request merged**
