### PR TITLE
Update post-integration workflow for dials-full

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
This pull request updates DialsScaler to use the updated behaviour introduced by dials/dials#859.

Rather than relying on hacks in dials.scale to produce all the output files for MAD data, use split experiments and individual calls to dials.export, dials.merge to get the datafiles.

Passes the tests and in theory makes things simpler :)

### CODE REVIEW

**Comment by graeme-winter** [comment]
Testing now

**Comment by graeme-winter** [comment]
For a simple case it looks to be giving _almost_ identical answers:

```
Grey-Area branch :) $ diff xia2.txt ../master/xia2.txt 
6,9c6,9
< CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpbyguVN
< Starting directory: /Users/graeme/data/i04-eiger-small/318/branch
< Working directory: /Users/graeme/data/i04-eiger-small/318/branch
< Free space:        21.07 GB
---
> CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpGilMAz
> Starting directory: /Users/graeme/data/i04-eiger-small/318/master
> Working directory: /Users/graeme/data/i04-eiger-small/318/master
> Free space:        19.65 GB
12,13c12,13
< XIA2 0.6.188-gc2ea2ff8-merge_refactor
< DIALS 2.dev.706-g60dc1df58
---
> XIA2 0.6.183-g1fc3c9f2
> DIALS 2.dev.696-gb0517ec4a
76c76
< MTZ file: /Users/graeme/data/i04-eiger-small/318/branch/DEFAULT/NATIVE/SWEEP1/integrate/dials_integrated.mtz
---
> MTZ file: /Users/graeme/data/i04-eiger-small/318/master/DEFAULT/NATIVE/SWEEP1/integrate/dials_integrated.mtz
90c90
< Wilson B factor                              10.148
---
> Wilson B factor                              10.150
102c102
< Scaled reflections: /Users/graeme/data/i04-eiger-small/318/branch/DataFiles/AUTOMATIC_DEFAULT_free.mtz
---
> Scaled reflections: /Users/graeme/data/i04-eiger-small/318/master/DataFiles/AUTOMATIC_DEFAULT_free.mtz
104,105c104,105
< Scaled reflections (NATIVE): /Users/graeme/data/i04-eiger-small/318/branch/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
< Processing took 00h 11m 55s
---
> Scaled reflections (NATIVE): /Users/graeme/data/i04-eiger-small/318/master/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
> Processing took 00h 11m 44s
```

**Comment by graeme-winter** [comment]
OK, ran through a MAD data set - slight differences (for the better?) in the merging stats but fewer reflections so suspect outliers wrangling. I note that the wavelengths are _wrong_ in master but _right_ in this branch, for the MTZ output. 

Same number of averaged reflections in each file. 

Absolute F values look similar:

```
Grey-Area 318 :) $ for j in 1 2 3 ; do grep "F  F_WAVE${j}" */mtz.dmp|sort -n; done
branch/mtz.dmp:   5 NONE    3.6  1514.9     1  100.00   110.48   110.48  55.66   1.33   F  F_WAVE1
master/mtz.dmp:   5 NONE    1.9  1518.5     0  100.00   110.38   110.38  55.66   1.33   F  F_WAVE1
branch/mtz.dmp:  20 NONE    2.6  1503.5     1  100.00   110.16   110.16  55.66   1.33   F  F_WAVE2
master/mtz.dmp:  20 NONE    1.3  1509.1     0  100.00   110.20   110.20  55.66   1.33   F  F_WAVE2
branch/mtz.dmp:  35 NONE    2.6  1479.0     1  100.00   108.54   108.54  55.66   1.33   F  F_WAVE3
master/mtz.dmp:  35 NONE    1.5  1482.8     0  100.00   108.49   108.49  55.66   1.33   F  F_WAVE3
```

So on the balance think we are good to go

**Comment by jbeilstenedmands** [comment]
Thanks, both PRs should be merged at the same time so I'll hit the buttons tomorrow morning and monitor any issues that arise.

**Comment by graeme-winter** [comment]
👍

**Comment by graeme-winter** [comment]
Quick question - how come 4 runs of two theta refine?

```
6873.9s  60. ┬     dials.two_theta_refine (25.2s)
6873.9s  61. │ ◯   dials.reindex (9.1s)
6899.1s      ┴ 
6899.2s  62. ┬     dials.two_theta_refine (26.0s)
6899.2s  63. │ ◯   dials.reindex (9.3s)
6925.1s      ┴ 
6925.2s  64. ┬     dials.two_theta_refine (23.9s)
6925.2s  65. │ ◯   dials.reindex (9.0s)
6949.0s      ┴ 
6949.1s  66. ┬     dials.two_theta_refine (70.0s)
6949.1s  67. │ ◯   dials.reindex (8.9s)
6958.0s  68. │ ◯   dials.reindex (9.0s)
6967.0s  69. │ ◯   dials.reindex (9.1s)
7019.1s      ┴ 
```

**Comment by graeme-winter** [comment]
Also, feature from CAD is that it renames crystals which do not have identical (or ~ identical) unit cells so we end up with:

```
 * Dataset ID, project/crystal/dataset names, cell dimensions, wavelength:

        1 DIALS
          DIALS
          FROMDIALS
             78.7208   78.7208   37.4679   90.0000   90.0000   90.0000
             0.91991
        2 DIALS
          DIALSrenamed
          FROMDIALS
             78.7503   78.7503   37.4827   90.0000   90.0000   90.0000
             0.92018
        3 DIALS
          DIALSrenamedrenamed
          FROMDIALS
             78.7605   78.7605   37.4884   90.0000   90.0000   90.0000
             0.91346
```

This is fine at the moment but since we have run two-theta refine we _could_ use the average cell for all sweeps as the cell here which would make this problem go away (and possibly - maybe - be more useful downstream).

**Comment by jbeilstenedmands** [comment]
Re two theta refine - was this a 3-wavelength MAD? Each dataset is refined individually and then all are refined together (looks like not much is done with the individual refinement apart from writing the results to chatter)

**Comment by graeme-winter** [comment]
Precisely this.

**Pull request merged**
