### PR TITLE
Run test in a temp dir to avoid PHIL droppings

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
This test creates the files xia2-diff.phil and xia2-working.phil.

### CODE REVIEW

**Review by rjgildea — APPROVED** [review]
Not sure newsfragment strictly necessary here (i.e. this is almost certainly not release note worthy), but probably doesn't cause any harm.

**Comment by benjaminhwilliams** [comment]
I have  feeling `misc` news doesn't get transliterated into the `CHANGELOG.rst`, it just lists the PR/issue number.

**Comment by benjaminhwilliams** [comment]
I might be wrong.  I'm assuming the configuration of Towncrier for xia2 is like that for screen19.

**Comment by Anthchirp** [comment]
the towncrier for xia2 will be following the schema for DIALS, ie. https://github.com/dials/dials/blob/master/newsfragments/README.MD

**Pull request merged**
